// server component
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import WagmiProvider from "./providers/wagmi-provider";
import { WalletStoreProvider } from "./providers/wallet-store-provider";
import { headers } from "next/headers";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = (await headers()).get("cookie");
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WagmiProvider cookie={cookie}>
          <WalletStoreProvider>{children}</WalletStoreProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
