// server component
import type { Metadata } from "next";
import WagmiProvider from "./providers/wagmi-provider";
import { WalletStoreProvider } from "./providers/wallet-store-provider";
import { headers } from "next/headers";
import "./globals.css";
import "@rainbow-me/rainbowkit/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = (await headers()).get("cookie");
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <WagmiProvider cookie={cookie}>
          <WalletStoreProvider>{children}</WalletStoreProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
